### ISSUE TITLE
I am unable to run using ZED2

### ISSUE THREAD

**Issue by Hyper-Devil** [appliedAI-Initiative/orb_slam_2_ros#104]
I modified the parameters such as Camera topics and camera_fx in the launch file, and it appears at run time: 
New map created with 268 points
[ WARN] [1615002039.816134264]: "zed2_camera_center" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1615002039.817486992]: "zed2_camera_center" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1615002039.872931648]: "zed2_camera_center" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1615002039.872990663]: "zed2_camera_center" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1615002039.919124112]: "zed2_camera_center" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1615002039.919181140]: "zed2_camera_center" passed to lookupTransform argument target_frame does not exist. 
There is no UI interface, how can I solve it?

Thanks for your answer.

**Comment by lennarthaller** [comment]
The launch file specifies the camera frame as:
`<param name="camera_frame_id" type="string" value="zed2_camera_center" />`
Make sure that this is matching your configuration.

**Comment by Hyper-Devil** [comment]
@lennarthaller  Thank you for your answer. As I am still a beginner, I sincerely hope you can give me more help.

I think the "camera_frame_id" is correct. Maybe there is something wrong with "target_frame_id", but I don't know how to solve it.

The TF tree maintained by zed_wrapper:
![frames](https://user-images.githubusercontent.com/35343157/110270122-1ecc6880-8000-11eb-9f3c-a250abe71d21.png)

The launch file I use:
```
<param name="pointcloud_frame_id" type="string" value="map" />
<param name="camera_frame_id" type="string" value="zed2_camera_center" />
<param name="target_frame_id" type="string" value="base_link" />
```
Launch file running result and new tf tree:
![sendpix0](https://user-images.githubusercontent.com/35343157/110270401-ab772680-8000-11eb-8a61-e68d9393268c.jpg)
![frames2](https://user-images.githubusercontent.com/35343157/110270460-cd70a900-8000-11eb-87a4-e0785b150c0f.png)


Could you give me some advice?
