### ISSUE TITLE
Build failure: No rule to make target libg2o.so

### ISSUE THREAD

**Issue by clydemcqueen** [appliedAI-Initiative/orb_slam_2_ros#118]
The ROS2 build sometimes fails due to a race condition, e.g., from https://github.com/clydemcqueen/orca3/issues/6:

~~~
make[2]: *** No rule to make target '/root/orca_ws/src/orb_slam_2_ros/orb_slam2/Thirdparty/g2o/lib/libg2o.so', needed by '/root/orca_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros_core.so'.  Stop.
~~~

The fix is to depend on the CMake targets `DBoW2` and `g2o`, not the `.so` files. I will submit a PR.

**Comment by lennarthaller** [comment]
Thanks!
