### ISSUE TITLE
Scale Estmation and Configuration

### ISSUE THREAD

**Issue by syhassan** [appliedAI-Initiative/orb_slam_2_ros#126]
Hello, I'm currently running monocular OrbSLAM2 with ROS Noetic on Ubuntu 20.04, and using Intel RealSense D455. OrbSLAM2 is configured to read parameters from the camera info topic. I mapped out the area around me and used Octomap for a grid map as shown in the following image:
![Screenshot from 2021-10-20 14-58-39](https://user-images.githubusercontent.com/47891763/138117334-c637f7e6-cd09-4463-8775-9b0a7058f775.png)

I seem to be having a problem with scaling, as you can see in the image below, the distance marked by the black line (almost in the centre of the image) is around 4 meters in real life, but unfortunately it comes to about 1 meter as shown in the bottom left corner of the image.
![Screenshot from 2021-10-20 14-58-18](https://user-images.githubusercontent.com/47891763/138118044-598f2cb1-12c1-43cd-8e1e-b0132a560c45.png)
 
Is there a way to change the scaling parameters for the node? I tried fiddling with the scaleFactor param but that seemed to me like mostly trial and error (it crashed when I set it to 4.8 instead of the default 1.2), so could you tell me how that functions?

**Comment by ojpc** [comment]
Hi @syhassan, did you find a way to rescale the map based on your real life measure?

**Comment by syhassan** [comment]
@ojpc unfortunately I did not :(
