### ISSUE TITLE
catkin build fails (Melodic)

### ISSUE THREAD

**Issue by GreatOnion1221** [appliedAI-Initiative/orb_slam_2_ros#136]
Hi 
When I run "catkin build" , I get the following error and it fails.
Can you please tell me the cause and what to do about it?

Errors     << orb_slam2_ros:make /home/gazebo/workspace/catkin_ws/logs/orb_slam2_ros/build.make.006.log     
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.406
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::RandomInt(int, int)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::SeedRandOnce()'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::SeedRandOnce(int)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::L'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::toArray8U(cv::Mat const&, unsigned char*)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::fromArray8U(cv::Mat&, unsigned char*)'
collect2: error: ld returned 1 exit status
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.406
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::RandomInt(int, int)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::SeedRandOnce()'
/home/gazebo/workspace/catkin_wsmake[2]: *** [/home/gazebo/workspace/catkin_ws/devel/.private/orb_slam2_ros/lib/orb_slam2_ros/orb_slam2_ros_mono] Error 1
/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::SeedRandOnce(intmake[1]: *** [CMakeFiles/orb_slam2_ros_mono.dir/all] Error 2
)'make[1]: *** Waiting for unfinished jobs....

/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::L'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::toArray8U(cv::Mat const&, unsigned char*)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::fromArray8U(cv::Mat&, unsigned char*)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/gazebo/workspace/catkin_ws/devel/.private/orb_slam2_ros/lib/orb_slam2_ros/orb_slam2_ros_rgbd] Error 1
make[1]: *** [CMakeFiles/orb_slam2_ros_rgbd.dir/all] Error 2
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.406
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::RandomInt(int, int)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::SeedRandOnce()'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DUtils::Random::SeedRandOnce(int)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::L'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::toArray8U(cv::Mat const&, unsigned char*)'
/home/gazebo/workspace/catkin_ws/src/orb_slam_2_ros/orb_slam2/lib/liborb_slam2_ros.so: undefined reference to `DBoW2::FORB::fromArray8U(cv::Mat&, unsigned char*)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/gazebo/workspace/catkin_ws/devel/.private/orb_slam2_ros/lib/orb_slam2_ros/orb_slam2_ros_stereo] Error 1
make[1]: *** [CMakeFiles/orb_slam2_ros_stereo.dir/all] Error 2
make: *** [all] Error 2
cd /home/gazebo/workspace/catkin_ws/build/orb_slam2_ros; catkin build --get-env orb_slam2_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -

**Comment by Quest2GM** [comment]
You can use `catkin_make_isolated`. The README says its an alternative.

**Comment by GreatOnion1221** [comment]
Quest2GM Thanks for the advice.
I was able to solve the problem by using the method in the link.
https://github.com/appliedAI-Initiative/orb_slam_2_ros/issues/43
