### ISSUE TITLE
Zed camera

### ISSUE THREAD

**Issue by arafatsh** [appliedAI-Initiative/orb_slam_2_ros#16]
I am using a zed camera, I made a .yaml file with my configurations and a launch file that corresponds to that file, when running it just stucks on this screen!
Any suggestions?   

![Screenshot from 2019-03-18 19-25-59](https://user-images.githubusercontent.com/47720756/54546079-0fd3f200-49b4-11e9-9f6d-92abc0076ebf.png)

**Comment by lennarthaller** [comment]
Seems to me like the SLAM is running but doesnt get any input. Do your topics match? Do you get the debug image from the SLAM in rviz?

**Comment by arafatsh** [comment]
Thanks for your respond, I think you are right.
This is my launch file 

![Screenshot from 2019-03-19 13-22-50](https://user-images.githubusercontent.com/47720756/54598692-20cf4280-4a4a-11e9-85e3-3b6c50ae69f9.png)

It should subscribe to /zed/left/image_rect_color and /zed/right/image_rect_color which is published by zed wrapper zed.start 

but still my launch file is not subscribing to those nodes but subscribing to others 

![Screenshot from 2019-03-19 13-23-45](https://user-images.githubusercontent.com/47720756/54598780-53793b00-4a4a-11e9-87ef-9022dd1c8ab6.png)

in Rviz there is no image 

Do you know how to fix that!?
Thanks in advance

**Comment by arafatsh** [comment]
Thank you for your respond, I had something wrong in the launch file.
Now its working.

**Comment by lennarthaller** [comment]
Yes, your topics were swapped in your remap. Please don't delete your messages and familiarize yourself with ros.

**Comment by arafatsh** [comment]
Exactly. 
you can close the issue.
thanks for your time

**Comment by arafatsh** [comment]
One more question, I can view the point cloud in RViz can I view in another program? or is there a way to download Orbslam2 : Mapviewer?

**Comment by lennarthaller** [comment]
No you can only use RViz for visualization.  Is there something missing you'd need?

**Comment by arafatsh** [comment]
Can the published pointcloud give us a RGB 3D map?

**Comment by lennarthaller** [comment]
No, a dense map is not published at this point.
