### ISSUE TITLE
Tracking Lost in KITTI Dataset

### ISSUE THREAD

**Issue by SubMishMar** [appliedAI-Initiative/orb_slam_2_ros#27]
Hi, I am trying to run this ros package with a bag file created on KITTI dataset but I find that the tracking is lost when the vehicle makes turns. How can I fix this? I want to know which params can be tuned.

**Comment by lennarthaller** [comment]
I find [this article](https://medium.com/@j.zijlmans/lsd-slam-vs-orb-slam2-a-literature-based-comparison-20732df431d) pretty helpful for a list of all the parameters and what they do. Hope that helps!
