### ISSUE TITLE
how to setup Camera.bf when using realsense D435i camera

### ISSUE THREAD

**Issue by wwtu** [appliedAI-Initiative/orb_slam_2_ros#28]
I am using realsensen D435i camera to run rgbd model. In the file you provided RealSenseD435RGBD.yaml, I am not sure the meaning of Camera.bf. You explained that it is "IR projector baseline times fx". Is the baseline that of the two IR cameras? what is the fx, is it the focal length of color camera or that of the IR camera, or that of the IR projector? Thanks.

**Comment by lennarthaller** [comment]
Specifically for the D435 the baseline is the one between the two IR cameras and fx is the focal length of the IR camera. This is because the IR cams are used to get the depth information, so the RGB cam is unimportant.
