### ISSUE TITLE
Interpreting TF values

### ISSUE THREAD

**Issue by spurohit01** [appliedAI-Initiative/orb_slam_2_ros#36]
Hi, 
Great library! Everything works very well. 

I am interested in comparing the localization output of the robot with data from sensors to measure the accuracy of ORB-SLAM. I noticed that one of the published topics is "tf". Does that return the robot's position with respect to world coordinates, the camera's starting position, etc? I am using the Monocular node. I would appreciate any guidance on how I might be able to compare the "tf" value with values from an AMCL system. 

Thank you very much!

**Comment by lennarthaller** [comment]
The tf value is the transformation from the starting position of the camera to the current position. If you want to compare the performance of the SLAM you need some form of ground truth to calculate the localization error. For this use one of the available ones such as the [TUM RGBD dataset](https://vision.in.tum.de/data/datasets/rgbd-dataset).
