### ISSUE TITLE
ros pose to orb pose

### ISSUE THREAD

**Issue by abylikhsanov** [appliedAI-Initiative/orb_slam_2_ros#38]
Do you know how to convert the ros pose (positon and rotation) to orb coordinate? As far as I understood, orb slam uses cv::Mat with 4x4 matrix and I have seen how the code converts that to ros system with posestamped message. What about other way round?

**Comment by lennarthaller** [comment]
From the code you should be able to invert the transformation mathematically and implement a invert function. Unfortunately I dont know the transform out of my head.
