### ISSUE TITLE
Wrong pose estimation when the scene is nearly planar and there is low parallax

### ISSUE THREAD

**Issue by moaljazaery** [appliedAI-Initiative/orb_slam_2_ros#39]
If  the camera is facing the ceiling and the robot has 2d move on the floor,  the  scene  is  nearly  planar  and  there  is  low parallax which makes  the pose estimation and the key frame selection to be not accurate.
Any suggestions?

**Comment by lennarthaller** [comment]
Then this algorithm is not suited for your use case. Don't point the camera to the ceiling or use something like optical flow.
