### ISSUE TITLE
Camera.bf of D435 is wrong 

### ISSUE THREAD

**Issue by dssdyx** [appliedAI-Initiative/orb_slam_2_ros#46]
Subscribe this topic /camera/extrinsics/depth_to_color and show the baseline from depth module to color is about 0.0146m. So, Camera.bf should be b x fx = 0.0146x620=9.052(resolution 640X480) not 49

dssdyx@dssdyx-OMEN-by-HP-Laptop-15-ce0xx:~$ rostopic echo /camera/extrinsics/depth_to_infra1
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "depth_to_infra1_extrinsics"
rotation: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
translation: [0.0, 0.0, 0.0]
---
^Cdssdyx@dssdyx-OMEN-by-HP-Laptop-15-ce0xx:~$ rostopic echo /camera/extrinsics/dth_to_infra2
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "depth_to_infra2_extrinsics"
rotation: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
translation: [-0.050028957426548004, 0.0, 0.0]
---
^Cdssdyx@dssdyx-OMEN-by-HP-Laptop-15-ce0xx:~$ rostopic echo /camera/extrinsics/dth_to_color 
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "depth_to_color_extrinsics"
rotation: [0.9999778270721436, 0.002401607343927026, -0.006211749743670225, -0.002392100403085351, 0.9999959468841553, 0.0015374466311186552, 0.006215416826307774, -0.0015225533861666918, 0.9999794960021973]
translation: [0.01459997147321701, -0.0001203833453473635, 0.00047532463213428855]

**Comment by lennarthaller** [comment]
Thanks for raising this, fixed it.
