### ISSUE TITLE
Where is "orb_slam2_mono" source file?

### ISSUE THREAD

**Issue by Allenhanbo** [appliedAI-Initiative/orb_slam_2_ros#55]
Hi all, I'm trying to understand the source code for this wrapper of orbslam2. When I was reading the launch file for mono part, I can not find the source file of orb_slam2_mono:       type="orb_slam2_ros_mono" output="screen">

Can anyone help me for this part? Thanks

**Comment by lennarthaller** [comment]
Its right here: https://github.com/appliedAI-Initiative/orb_slam_2_ros/blob/master/ros/src/MonoNode.cc

**Comment by Allenhanbo** [comment]
Thanks!
