### ISSUE TITLE
No GUI created when running orb_slam_2_ros

### ISSUE THREAD

**Issue by JChunX** [appliedAI-Initiative/orb_slam_2_ros#56]
Hi, I am running orb_slam_2_ros with the monocular node on ros melodic. The camera stream seems to be working as rqt_image_view displays the /camera/image_raw images correctly, however I don’t see the orb_slam_2 GUI that comes with running non ros orb_slam_2. What am I doing wrong? Thank you.

**Comment by lennarthaller** [comment]
Next time please read the README or look in the isseues already posted: #4
