### ISSUE TITLE
catkin command not found

### ISSUE THREAD

**Issue by D7823** [appliedAI-Initiative/orb_slam_2_ros#60]
I am not familiar with the ccatkin tools and it came out this error when I tried to build the package. But the previous rosdep steps said all deficiencies built. I wonder why it happens and how to solve it?

Thanks in advance.

**Comment by lennarthaller** [comment]
Seems like you don't have the [catkin tools](https://catkin-tools.readthedocs.io/en/latest/installing.html) installed.  But this is really not a question for the repo but a general ROS forum.
