### ISSUE TITLE
Launch files use missing settings files

### ISSUE THREAD

**Issue by tim-fan** [appliedAI-Initiative/orb_slam_2_ros#63]
Hi there, thanks for the awesome package :smile: 

It looks like all of the [launch files](https://github.com/appliedAI-Initiative/orb_slam_2_ros/tree/master/ros/launch) are setting the `settings_file` parameter to point to configs under `orb_slam2/config` [(example),](https://github.com/appliedAI-Initiative/orb_slam_2_ros/blob/master/ros/launch/orb_slam2_d435_rgbd.launch#L16) however this whole directory was recently deleted in [e0e18ae06](https://github.com/appliedAI-Initiative/orb_slam_2_ros/commit/e0e18ae06ec27a8a030709a31d1aa644d59dfd21), so these configs do not exist.

I guess all the launch files should be updated to no longer set the `settings_file` parameter?

**Comment by lennarthaller** [comment]
You are totally right, just merged your PR.
