### ISSUE TITLE
How to reset localization after tracking lost.  

### ISSUE THREAD

**Issue by sarath-vanga** [appliedAI-Initiative/orb_slam_2_ros#73]
Hi,

I use orbslam2 just for the purpose of visual odometry. When working with different datasets, I have observed that sometimes the tracking is lost and localization is stopped completely. 

Is it possible in orbslam2 to reset localization/odometry when tracking is lost?

**Comment by caiofis** [comment]
There is a parameter to reset the map, you just have to set it to true. It is automatically set to false after the reset. You can do this using rqt_reconfigure or with the command line tool as follows:
`rosparam set /orb_slam2_mono/reset_map true`
