### ISSUE TITLE
Orb-vocabulary saved in bin file too?

### ISSUE THREAD

**Issue by isVoid** [appliedAI-Initiative/orb_slam_2_ros#74]
Hi, when called `save_map`, will the orb-bow vocabulary also get saved in the bin file? When the system is launched with `/map_file` param, does setting "voc_file" make any difference at all?

Thank you very much for your answer!

**Comment by lennarthaller** [comment]
The orb-bow vocabulary will not be saved in the bin file and needs to be reloaded from the vocab file separately when loading the map.
