### ISSUE TITLE
fatal error: orb_slam2_ros/SaveMap.h Not such File or Directory

### ISSUE THREAD

**Issue by juniorschen** [appliedAI-Initiative/orb_slam_2_ros#76]
![image](https://user-images.githubusercontent.com/46031261/87230082-9ff53200-c383-11ea-94e6-046b092271f4.png)
When i use catkin_make i recive this error, in orb_slam2_ros/ not have the SaveMap.h

**Comment by juniorschen** [comment]
Somehow I managed to finish the build, however when trying to execute:
roslaunch orb_slam2_ros orb_slam2_r200_mono.launch
I have the following problem:
![image](https://user-images.githubusercontent.com/46031261/87236368-fcc20e00-c3be-11ea-849b-eb956f3b99dc.png)
I'm following this short tutorial (I don't understand why we don't have a better step by step of these ROS packages, people "not very smart" like me end up having a lot of problems before using the tool minimum because of that):
https://www.hackadda.com/post/2020/5/17/using-orb-slam-ros-to-map-the-world

**Comment by juniorschen** [comment]
Running turtlebot3 i have the image topics necessary:
![image](https://user-images.githubusercontent.com/46031261/87236394-68a47680-c3bf-11ea-9e9e-b4165aa2139b.png)

**Comment by juniorschen** [comment]
Complete Log:

[roslaunch][INFO] 2020-07-11 21:52:09,353: Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2020-07-11 21:52:09,357: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2020-07-11 21:52:09,357: roslaunch starting with args ['/opt/ros/kinetic/bin/roslaunch', 'orb_slam2_ros', 'orb_slam2_r200_mono.launch']
[roslaunch][INFO] 2020-07-11 21:52:09,357: roslaunch env is {'TURTLEBOT_TYPE': 'turtlebot', 'ROS_DISTRO': 'kinetic', 'TURTLEBOT_STAGE_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/stage/maze.world', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'TURTLEBOT_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_navigation/maps/willow-2010-02-18-0.10.yaml', 'ROSLISP_PACKAGE_DIRECTORIES': '/root/catkin_ws/devel/share/common-lisp', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'PATH': '/opt/ros/kinetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'CMAKE_PREFIX_PATH': '/root/catkin_ws/devel:/opt/ros/kinetic', 'LD_LIBRARY_PATH': '/root/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu', 'TURTLEBOT_STDR_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stdr/maps/sparse_obstacles.yaml', 'LANG': 'pt_BR.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'ROS_LOG_FILENAME': '/root/.ros/log/7606b5ea-c3ce-11ea-a879-080027e5d2a9/roslaunch-rosu-VirtualBox-6719.log', 'XAUTHORITY': '/home/rosu/.Xauthority', 'LANGUAGE': 'pt_BR:pt:en', 'TURTLEBOT_STACKS': 'hexagons', 'SHLVL': '1', 'TURTLEBOT_SIMULATION': 'false', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'DISPLAY': ':0', 'TURTLEBOT_RAPP_PACKAGE_WHITELIST': '[rocon_apps, turtlebot_rapps]', 'TURTLEBOT_BATTERY': '/sys/class/power_supply/BAT1', 'SUDO_USER': 'rosu', 'TURTLEBOT_INTERACTIONS_LIST': '[turtlebot_bringup/admin.interactions, turtlebot_bringup/documentation.interactions, turtlebot_bringup/pairing.interactions, turtlebot_bringup/visualisation.interactions]', 'ROS_PYTHON_VERSION': '2', 'USERNAME': 'root', 'TURTLEBOT_RAPP_PACKAGE_BLACKLIST': '[]', 'PYTHONPATH': '/root/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages', 'SUDO_UID': '1000', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'TURTLEBOT_GAZEBO_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/maps/playground.yaml', 'PKG_CONFIG_PATH': '/root/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig', 'ROS_PACKAGE_PATH': '/root/catkin_ws/src:/opt/ros/kinetic/share', 'TURTLEBOT_STAGE_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/maze.yaml', 'TURTLEBOT_SERIAL_PORT': '/dev/kobuki', 'TURTLEBOT_BASE': 'kobuki', '_': '/opt/ros/kinetic/bin/roslaunch', 'SUDO_COMMAND': '/bin/su', 'SUDO_GID': '1000', 'TURTLEBOT_NAME': 'turtlebot', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'OLDPWD': '/root/catkin_ws/src/orb_slam_2_ros/orb_slam2', 'ROS_IP': '192.168.15.10', 'PWD': '/root/catkin_ws/src/orb_slam_2_ros', 'TURTLEBOT_GAZEBO_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/worlds/playground.world', 'ROS_MASTER_URI': 'http://192.168.15.10:11311', 'TURTLEBOT_3D_SENSOR': 'astra', 'ROS_VERSION': '1', 'MAIL': '/var/mail/root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}
[roslaunch][INFO] 2020-07-11 21:52:09,357: starting in server mode
[roslaunch.parent][INFO] 2020-07-11 21:52:09,358: starting roslaunch parent run
[roslaunch][INFO] 2020-07-11 21:52:09,358: loading roscore config file /opt/ros/kinetic/etc/ros/roscore.xml
[roslaunch][INFO] 2020-07-11 21:52:09,550: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2020-07-11 21:52:09,550: loading config file /root/catkin_ws/src/orb_slam_2_ros/ros/launch/orb_slam2_r200_mono.launch
[roslaunch][INFO] 2020-07-11 21:52:09,591: Added node of type [orb_slam2_ros/orb_slam2_ros_mono] in namespace [/]
[roslaunch][INFO] 2020-07-11 21:52:09,591: ... selected machine [] for node of type [orb_slam2_ros/orb_slam2_ros_mono]
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,592: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,592: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,592: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2020-07-11 21:52:09,592: starting parent XML-RPC server
[roslaunch.server][INFO] 2020-07-11 21:52:09,592: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2020-07-11 21:52:09,592: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2020-07-11 21:52:09,592: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-07-11 21:52:09,593: Started XML-RPC server [http://192.168.15.10:41303/]
[xmlrpc][INFO] 2020-07-11 21:52:09,593: xml rpc node: starting XML-RPC server
[roslaunch][INFO] 2020-07-11 21:52:09,610: started roslaunch server http://192.168.15.10:41303/
[roslaunch.parent][INFO] 2020-07-11 21:52:09,610: ... parent XML-RPC server started
[roslaunch][INFO] 2020-07-11 21:52:09,610: master.is_running[http://192.168.15.10:11311]
[roslaunch][INFO] 2020-07-11 21:52:09,611: master.is_running[http://192.168.15.10:11311]
[roslaunch][INFO] 2020-07-11 21:52:09,612: ROS_MASTER_URI=http://192.168.15.10:11311
[roslaunch][INFO] 2020-07-11 21:52:09,614: setting /roslaunch/uris/host_192_168_15_10__41303' to http://192.168.15.10:41303/
[roslaunch][INFO] 2020-07-11 21:52:09,615: load_parameters starting ...
[roslaunch][INFO] 2020-07-11 21:52:09,624: ... load_parameters complete
[roslaunch][INFO] 2020-07-11 21:52:09,624: launch_nodes: launching local nodes ...
[roslaunch][INFO] 2020-07-11 21:52:09,624: ... preparing to launch node of type [orb_slam2_ros/orb_slam2_ros_mono]
[roslaunch][INFO] 2020-07-11 21:52:09,624: create_node_process: package[orb_slam2_ros] type[orb_slam2_ros_mono] machine[Machine(name[] env_loader[None] address[localhost] ssh_port[22] user[None] assignable[True] timeout[10.0])] master_uri[http://192.168.15.10:11311]
[roslaunch][INFO] 2020-07-11 21:52:09,624: process[orb_slam2_mono-1]: env[{'TURTLEBOT_TYPE': 'turtlebot', 'ROS_DISTRO': 'kinetic', 'TURTLEBOT_STAGE_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/stage/maze.world', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'TURTLEBOT_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_navigation/maps/willow-2010-02-18-0.10.yaml', 'ROSLISP_PACKAGE_DIRECTORIES': '/root/catkin_ws/devel/share/common-lisp', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'PATH': '/opt/ros/kinetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'CMAKE_PREFIX_PATH': '/root/catkin_ws/devel:/opt/ros/kinetic', 'ROS_LOG_FILENAME': '/root/.ros/log/7606b5ea-c3ce-11ea-a879-080027e5d2a9/roslaunch-rosu-VirtualBox-6719.log', 'TURTLEBOT_STDR_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stdr/maps/sparse_obstacles.yaml', 'LANG': 'pt_BR.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XAUTHORITY': '/home/rosu/.Xauthority', 'LANGUAGE': 'pt_BR:pt:en', 'TURTLEBOT_STACKS': 'hexagons', 'SHLVL': '1', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'TURTLEBOT_SIMULATION': 'false', 'LD_LIBRARY_PATH': '/root/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu', 'TURTLEBOT_RAPP_PACKAGE_WHITELIST': '[rocon_apps, turtlebot_rapps]', 'ROS_MASTER_URI': 'http://192.168.15.10:11311', 'SUDO_USER': 'rosu', 'TURTLEBOT_INTERACTIONS_LIST': '[turtlebot_bringup/admin.interactions, turtlebot_bringup/documentation.interactions, turtlebot_bringup/pairing.interactions, turtlebot_bringup/visualisation.interactions]', 'ROS_PYTHON_VERSION': '2', 'USERNAME': 'root', 'ROS_VERSION': '1', 'PYTHONPATH': '/root/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages', 'SUDO_UID': '1000', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'PWD': '/root/catkin_ws/src/orb_slam_2_ros', 'TURTLEBOT_GAZEBO_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/maps/playground.yaml', 'PKG_CONFIG_PATH': '/root/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig', 'ROS_PACKAGE_PATH': '/root/catkin_ws/src:/opt/ros/kinetic/share', 'TURTLEBOT_STAGE_MAP_FILE': '/opt/ros/kinetic/share/turtlebot_stage/maps/maze.yaml', 'TURTLEBOT_SERIAL_PORT': '/dev/kobuki', 'TURTLEBOT_BASE': 'kobuki', '_': '/opt/ros/kinetic/bin/roslaunch', 'SUDO_COMMAND': '/bin/su', 'SUDO_GID': '1000', 'TURTLEBOT_NAME': 'turtlebot', 'DISPLAY': ':0', 'OLDPWD': '/root/catkin_ws/src/orb_slam_2_ros/orb_slam2', 'ROS_IP': '192.168.15.10', 'TURTLEBOT_BATTERY': '/sys/class/power_supply/BAT1', 'TURTLEBOT_GAZEBO_WORLD_FILE': '/opt/ros/kinetic/share/turtlebot_gazebo/worlds/playground.world', 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', 'TURTLEBOT_3D_SENSOR': 'astra', 'TURTLEBOT_RAPP_PACKAGE_BLACKLIST': '[]', 'MAIL': '/var/mail/root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}]
[roslaunch][INFO] 2020-07-11 21:52:09,689: process[orb_slam2_mono-1]: args[[u'/root/catkin_ws/devel/lib/orb_slam2_ros/orb_slam2_ros_mono', u'/camera/rgb/image_raw:=/camera/rgb/image_raw', u'__name:=orb_slam2_mono']]
[roslaunch][INFO] 2020-07-11 21:52:09,689: ... created process [orb_slam2_mono-1]
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,689: ProcessMonitor.register[orb_slam2_mono-1]
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,689: ProcessMonitor.register[orb_slam2_mono-1] complete
[roslaunch][INFO] 2020-07-11 21:52:09,689: ... registered process [orb_slam2_mono-1]
[roslaunch][INFO] 2020-07-11 21:52:09,689: process[orb_slam2_mono-1]: starting os process
[roslaunch][INFO] 2020-07-11 21:52:09,689: process[orb_slam2_mono-1]: start w/ args [[u'/root/catkin_ws/devel/lib/orb_slam2_ros/orb_slam2_ros_mono', u'/camera/rgb/image_raw:=/camera/rgb/image_raw', u'__name:=orb_slam2_mono', u'__log:=/root/.ros/log/7606b5ea-c3ce-11ea-a879-080027e5d2a9/orb_slam2_mono-1.log']]
[roslaunch][INFO] 2020-07-11 21:52:09,689: process[orb_slam2_mono-1]: cwd will be [/root/.ros]
[roslaunch][ERROR] 2020-07-11 21:52:09,695: OSError(8, Exec format error)
[roslaunch][ERROR] 2020-07-11 21:52:09,695: Unable to launch [orb_slam2_mono-1]. 
If it is a script, you may be missing a '#!' declaration at the top.
[roslaunch][ERROR] 2020-07-11 21:52:09,695: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2020-07-11 21:52:09,696: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 658, in launch
    succeeded, failed = self._launch_nodes()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 367, in _launch_nodes
    proc, success = self.launch_node(node)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/launch.py", line 557, in launch_node
    success = process.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/nodeprocess.py", line 309, in start
    raise FatalProcessLaunch("Unable to launch [%s]. \nIf it is a script, you may be missing a '#!' declaration at the top."%self.name)
FatalProcessLaunch: Unable to launch [orb_slam2_mono-1]. 
If it is a script, you may be missing a '#!' declaration at the top.

[roslaunch.pmon][INFO] 2020-07-11 21:52:09,696: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, started daemon 139970050221824)>
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,795: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 139970050221824)>
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,795: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 139970050221824)>: remaining procs are [<roslaunch.nodeprocess.LocalProcess object at 0x7f4d516abad0>]
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,796: ProcessMonitor exit: killing orb_slam2_mono-1
[roslaunch][INFO] 2020-07-11 21:52:09,796: [orb_slam2_mono-1] killing on exit
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,801: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2020-07-11 21:52:09,801: ProcessMonitor exit: pmon has shutdown
[rospy.core][INFO] 2020-07-11 21:52:09,813: signal_shutdown [atexit]

**Comment by juniorschen** [comment]
Well after a torturous day of trying (I even tried to configure it by the main ORB_SLAM project but the hell of my virtual machine always caused memory problems when building), I finally got to the point of the tutorial I used, and how did I do it? I simply deleted the clone from the repository and did it again and everything works, sometimes I think that hell does not exist, until I have to work with problems like this in linux / ros

**Comment by Wingmore** [comment]
> When i use catkin_make i recive this error, in orb_slam2_ros/ not have the SaveMap.h

How did you fix this issue? I'm getting the same one

**Comment by juniorschen** [comment]
@Wingmore 
I deleted the package, went to the real project and installed all the dependencies he mentions and performed the build, after that I downloaded the ros package again and it worked

git: https://github.com/raulmur/ORB_SLAM2
dependencies:
![image](https://user-images.githubusercontent.com/46031261/91435726-2931cc80-e83d-11ea-9599-48a13e5b074e.png)

**Comment by mcmchammer** [comment]
Hi - I'm hitting the same issue, but missing a root cause in this thread ... any insights regarding what exactly is causing this error?

**Comment by AnaRhisT94** [comment]
> In case anyone is running into this, this error arises from missing message generation dependencies for the build targets in CMakeLists.txt; add `${PROJECT_NAME}_generate_messages_cpp` to the dependencies as follows
> 
> ```
> ...
> add_dependencies (${PROJECT_NAME}_mono ${PROJECT_NAME} ${PROJECT_NAME}_gencfg ${PROJECT_NAME}_generate_messages_cpp)
> ...
> add_dependencies (${PROJECT_NAME}_stereo ${PROJECT_NAME} ${PROJECT_NAME}_gencfg ${PROJECT_NAME}_generate_messages_cpp)
> ...
> add_dependencies (${PROJECT_NAME}_rgbd ${PROJECT_NAME} ${PROJECT_NAME}_gencfg ${PROJECT_NAME}_generate_messages_cpp)
> ...
> ```

This actually solved my issue and I successfully built catkin.
Here the complete CMAKELists.txt file: (using ROS Melodic)

```
cmake_minimum_required(VERSION 2.8.3)
project(orb_slam2_ros)

IF(NOT CMAKE_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE Release)
ENDIF()

# Check for c++11 support
INCLUDE(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
IF(COMPILER_SUPPORTS_CXX11)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
   add_definitions(-DCOMPILEDWITHC11)
   message(STATUS "Using flag -std=c++11.")
elseif(COMPILER_SUPPORTS_CXX0X)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
   add_definitions(-DCOMPILEDWITHC0X)
   message(STATUS "Using flag -std=c++0x.")
ELSE()
  MESSAGE(ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
ENDIF()

LIST(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/orb_slam2/cmake_modules)

find_package (catkin REQUIRED COMPONENTS
roscpp
rospy
std_msgs
cv_bridge
image_transport
tf
sensor_msgs
dynamic_reconfigure
message_generation
)

find_package(OpenCV 3.0 QUIET)
if(NOT OpenCV_FOUND)
   find_package(OpenCV 2.4.3 QUIET)
   if(NOT OpenCV_FOUND)
      message(FATAL_ERROR "OpenCV > 2.4.3 not found.")
   endif()
endif()



find_package(Eigen3 3.1.0 REQUIRED)
find_package(Pangolin REQUIRED)

set (DYNAMIC_RECONFIGURE_PATH ros/config/dynamic_reconfigure.cfg)
execute_process(COMMAND chmod a+x ${DYNAMIC_RECONFIGURE_PATH}
        WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
        RESULT_VARIABLE cmd_result
        OUTPUT_VARIABLE cmd_ver)
message(STATUS "Chmod a+x the dynamic_reconfigure file")

generate_dynamic_reconfigure_options(
        ${DYNAMIC_RECONFIGURE_PATH}
)

set(LIBS_ORBSLAM
${OpenCV_LIBS}
${EIGEN3_LIBS}
${PROJECT_SOURCE_DIR}/orb_slam2/Thirdparty/DBoW2/lib/libDBoW2.so
${PROJECT_SOURCE_DIR}/orb_slam2/Thirdparty/g2o/lib/libg2o.so
)

set(LIBS_ROS
${PROJECT_SOURCE_DIR}/orb_slam2/lib/lib${PROJECT_NAME}.so
${OpenCV_LIBS}
${catkin_LIBRARIES}
)

add_service_files(
        FILES
        SaveMap.srv
)

generate_messages(
        DEPENDENCIES
        std_msgs
)

catkin_package (
  CATKIN_DEPENDS roscpp rospy std_msgs cv_bridge image_transport tf sensor_msgs dynamic_reconfigure message_runtime
  LIBRARIES {PROJECT_NAME} libDBoW2 libg2o
)

include_directories(
${PROJECT_SOURCE_DIR}/orb_slam2
${PROJECT_SOURCE_DIR}/orb_slam2/include
${PROJECT_SOURCE_DIR}/ros/include
${EIGEN3_INCLUDE_DIR}
${Pangolin_INCLUDE_DIRS}
${catkin_INCLUDE_DIRS}
)

include(${PROJECT_SOURCE_DIR}/orb_slam2/Thirdparty/DBoW2/CMakeLists.txt)
include(${PROJECT_SOURCE_DIR}/orb_slam2/Thirdparty/g2o/CMakeLists.txt)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/orb_slam2/lib)

add_library(${PROJECT_NAME} SHARED
orb_slam2/src/System.cc
orb_slam2/src/Tracking.cc
orb_slam2/src/LocalMapping.cc
orb_slam2/src/LoopClosing.cc
orb_slam2/src/ORBextractor.cc
orb_slam2/src/ORBmatcher.cc
orb_slam2/src/FrameDrawer.cc
orb_slam2/src/Converter.cc
orb_slam2/src/MapPoint.cc
orb_slam2/src/KeyFrame.cc
orb_slam2/src/Map.cc
orb_slam2/src/MapDrawer.cc
orb_slam2/src/Optimizer.cc
orb_slam2/src/PnPsolver.cc
orb_slam2/src/Frame.cc
orb_slam2/src/KeyFrameDatabase.cc
orb_slam2/src/Sim3Solver.cc
orb_slam2/src/Initializer.cc
orb_slam2/src/Viewer.cc
)
add_dependencies (${PROJECT_NAME} g2o DBoW2 ${PROJECT_NAME}_generate_messages_cpp)

target_link_libraries(${PROJECT_NAME}
${LIBS_ORBSLAM}
${Pangolin_LIBRARIES}
)

# map serialization addition - library boost serialization 
message(STATUS "Compile With map save/load function")
find_library(BOOST_SERIALIZATION boost_serialization)
if (NOT BOOST_SERIALIZATION)
    message(FATAL_ERROR "Can't find libboost_serialization")
endif()
target_link_libraries(${PROJECT_NAME} ${BOOST_SERIALIZATION})

add_executable (${PROJECT_NAME}_mono
ros/src/MonoNode.cc
ros/src/Node.cc
)
add_dependencies (${PROJECT_NAME}_mono ${PROJECT_NAME} ${PROJECT_NAME}_gencfg ${PROJECT_NAME}_generate_messages_cpp)

target_link_libraries(${PROJECT_NAME}_mono
${LIBS_ROS}
${Pangolin_LIBRARIES}
)

add_executable (${PROJECT_NAME}_stereo
ros/src/StereoNode.cc
ros/src/Node.cc
)
#add_dependencies (${PROJECT_NAME}_stereo ${PROJECT_NAME} ${PROJECT_NAME}_gencfg)

target_link_libraries(${PROJECT_NAME}_stereo
${LIBS_ROS}
${Pangolin_LIBRARIES}
)

add_executable (${PROJECT_NAME}_rgbd
ros/src/RGBDNode.cc
ros/src/Node.cc
)
#add_dependencies (${PROJECT_NAME}_rgbd ${PROJECT_NAME} ${PROJECT_NAME}_gencfg)

target_link_libraries(${PROJECT_NAME}_rgbd
${LIBS_ROS}
${Pangolin_LIBRARIES}
)

message(STATUS "printing CATKIN_PACKAGE_LIB_DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}" )
message(STATUS "printing CATKIN_PACKAGE_BIN_DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}" )

install(TARGETS ${PROJECT_NAME}_mono ${PROJECT_NAME}_stereo ${PROJECT_NAME}_rgbd
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)

install(TARGETS ${PROJECT_NAME} DBoW2 g2o
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)

install(DIRECTORY ros/launch/
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/ros/launch
)

install(DIRECTORY ros/config/
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/ros/config
)

install(DIRECTORY orb_slam2/config/
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/orb_slam2/config
)

install(DIRECTORY orb_slam2/Vocabulary/
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/orb_slam2/Vocabulary
)
```

**Comment by arjunskumar** [comment]
@AnaRhisT94 Thank you _/\_
