### ISSUE TITLE
Stuck on wrong initialization

### ISSUE THREAD

**Issue by BenedettoGinestra** [appliedAI-Initiative/orb_slam_2_ros#78]
Hi everyone!
I recently installed your package for ros melodic and I am trying to build a map of an outdoor scenario in gazebo.
Anyway, the initialization lasts long and, at some point, it seems to reset because of some trouble.
```

Map point vector is empty!
Map point vector is empty!
Map point vector is empty!
New Map created with 83 points
Wrong initialization, reseting...
System Reseting
Reseting Local Mapper... done
Reseting Loop Closing... done
Reseting Database... done
Map point vector is empty!
Map point vector is empty!
```
This is what I get in the terminal output - have you any idea what it could be? 
Thanks in advance for your time.

P.S. My scenario is a large outdoor soccer field

**Comment by lennarthaller** [comment]
> My scenario is a large outdoor soccer field

This and the the "Map point vector is empty" message tell me that the SLAM does not find enough features to process similar to #83. A soccer field doesn't have much (close) features especially in the case of players moving.
Is a (stereo) fisheye lens an option? Think thats your best shot.
