### ISSUE TITLE
scale of tf

### ISSUE THREAD

**Issue by E-pep** [appliedAI-Initiative/orb_slam_2_ros#8]
Hello, 
I've got the algorithm working, thank you for that! But I have a question about the transformation. So the algorithm sends a tf with map as parent, when I translate the camera I get translations in the range like for example 0.147. Is this 0.147 meters then or am I wrong?

**Comment by lennarthaller** [comment]
Hey, 
yes, the tf is in meters. But the scale is only correct if you use a stereo or RGBD camera. The scale is influenced by the DepthMapFactor in the config file which needs to be set correctly.

**Comment by E-pep** [comment]
Thanks you for the information
