### ISSUE TITLE
Parameters changing

### ISSUE THREAD

**Issue by hamjs0724** [appliedAI-Initiative/orb_slam_2_ros#80]
Hi, I'm a student from Korea and I'm not good at hadling programming tools, frankly. (also github community.)

How do you change the parameters before run the launch files like 'orb_slam2_d435_rgbd.launch'?

I wanted to load the map file which is I saved on rviz.
So I tried to change parameters with '{parameter name} := {value}' form like below.

localize_only:=true
map_file:=(my map path)
load_map:=true

but when I run it, the prompt showed me the not-changed parameters.

so I just fix the lines of the launch file before running every time and it really bothers me..
Now, I save some files for each situations and run what I need.

1. What am I supposed to do to change the parameters on terminal?
2. Is there a way to just show the pointcloud2 map on rviz?

Sorry about my not good English and very basic question. I hope you catch what I mean.

**Comment by lennarthaller** [comment]
The map file param needs to be provided on startup, so the launch file is the best option. If you want to load a different map you need to restart the node anyway.
> but when I run it, the prompt showed me the not-changed parameters.
Sounds like you are expecting the parameters to persistent?
ROS is using the ROS parameter server which is by default being started (and killed..) together with the ROS master. 
If you change parameter via command line and restart the node with the launch file the parameters you set are being overwritten by the launch file. 
I suggest you familiarize yourself with ROS and the parameter system.
> Is there a way to just show the pointcloud2 map on rviz?
By default the node will output a pointcloud2 which you can look at in Rviz.
