### ISSUE TITLE
Offline map optimization

### ISSUE THREAD

**Issue by cesar-lopez-mar** [appliedAI-Initiative/orb_slam_2_ros#85]
Hello,

I would like to make a map of an indoor environment and afterwards use the "tracking-only" mode. Currently I drove manually a couple of loops around the room to make a map. Despite that loop closure is detected and the Global Bundle Adjustment (GBA) routine performed (I pause driving during this GBA), the map seems to have quite some drift. Reading literature it seems that many researchers do offline map optimization by running the algorithm several times over a loop sequence, including also reverse play back. I was wondering if you have tools available to perform such offline map optimization.

**Comment by lennarthaller** [comment]
Right now we don't have any such tools available. if you use a mono camera I recommend using a stereo or RGBD. Also check if your camera calibration is correct. Try adding more (interconnected) loops to the dataset.
