### ISSUE TITLE
Visual odometry

### ISSUE THREAD

**Issue by leechangyo** [appliedAI-Initiative/orb_slam_2_ros#87]
hi, I want to use it at turtlbot3 in the gazebo.

and I wonder here the camera pose is the same as visual odometry?

I want to use it for navigation

can I use camera pose data for visual odometry?

**Comment by lennarthaller** [comment]
Please familiarize yourself with the tf concepts of ROS: https://www.ros.org/reps/rep-0105.html. Odometry needs to be continuous ("jump free"). Loops closing (optimizing the pose graph) introduces jumps which break the odometer constraint. You could try to disable the optimization for orb_slam but Id rather recommend a visual odometry algorithm like DSO.
