### ISSUE TITLE
Process has died when run mono odometer

### ISSUE THREAD

**Issue by juniorschen** [appliedAI-Initiative/orb_slam_2_ros#88]
Hi guys, I'm trying to do a simple project where I collect data on how a raspicam performs in a slam process, I'm using some algorithms, but when using orb my finish has this message of death of the process:
![image](https://user-images.githubusercontent.com/46031261/96352667-52334880-109b-11eb-8d5b-eb427721941f.png)
I can't find any specific message about what is causing the error ...
I'm using the knots from (http://wiki.ros.org/uvc_camera) to capture the images, I did the calibration.
I edited one of the orb launch files to be able to use the correct topics and use my camera_info:
![image](https://user-images.githubusercontent.com/46031261/96352706-b2c28580-109b-11eb-8828-cdb175b30e11.png)
I can already use the algorithm using the turtle_bot simulator, everything went well

Would anyone have any way to help me? Even in the ROS logs I only find this damn message "Process has died", another important information is that I am processing the data on a desktop, my raspberry only captures the images

**Comment by lennarthaller** [comment]
Map point vector empty means the mono slam is not initialized. See #2. This is likely what's causing the crash.
