### ISSUE TITLE
/camera/image_raw not subscribing to /videofile/image_raw

### ISSUE THREAD

**Issue by stephennacion06** [appliedAI-Initiative/orb_slam_2_ros#90]
Hello, I am trying to do **roslaunch orb_slam2_ros orb_slam2_r200_mono.launch /camera/image_raw:=/videofile/image_raw** but there is still no images displaying both rviz and image view to orb slam 2

**Comment by stephennacion06** [comment]
![image](https://user-images.githubusercontent.com/32524849/97114315-cbc9d700-172a-11eb-9cf7-f1f531b1e3c3.png)

**Comment by lennarthaller** [comment]
Have you looked at the terminal log of the node? Seems like #2. Mono slam from a video file where the slam can't initialize is gonna be tough.

**Comment by stephennacion06** [comment]
Okay thank you for the reply and for your work. The issue is fix by changing the /camera/image_raw to /videofile/image_raw inside the Mononode.cc
![image](https://user-images.githubusercontent.com/32524849/97698584-b0bce580-1ae3-11eb-9223-b52f4d82852e.png)
