### ISSUE TITLE
How to view trajectory in real time

### ISSUE THREAD

**Issue by yx0123** [appliedAI-Initiative/orb_slam_2_ros#95]
Is there any way to view the trajectory in real time using rviz? Seems like rviz requires nav_msgs/Path but the package publishes to /orb_slam2_rgbd/pose which is geometry_msgs/PoseStamped

**Comment by Gautham-JS** [comment]
Hey, 
nav_msgs/Path is simply a vector of PoseStamped messages previously published. You can write a simple subscriber for PoseStamped from `/orb_slam2_rgbd/pose` and repack it into a nav_msgs/Path message then publish it over a new topic. 

PS: the published topic `/orb_slam2_rgbd/pose` publishes instantaneous pose so in cases of loop closure and map/pose updation you'll probably get an abrupt break in `nav_msgs/Path` youre publishing on your own.
